CREATE TABLE IF NOT EXISTS pictures (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    description VARCHAR(512)                      NOT NULL
);
